# Generated by Django 5.1.3 on 2024-11-21 03:16

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0001_initial"),
    ]

    operations = [VectorExtension()]
