# Generated by Django 5.1.3 on 2024-11-21 03:25

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0002_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Embedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField()),
                ("dimensions", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="index",
            name="dimensions",
            field=models.IntegerField(default=768),
        ),
        migrations.AlterField(
            model_name="index",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="indexeddocumentsnippet",
            unique_together={("index", "document", "snippet")},
        ),
        migrations.AddField(
            model_name="indexeddocumentsnippet",
            name="embedding",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="indexing.embedding",
            ),
        ),
    ]
