# Generated by Django 5.1.3 on 2024-11-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indexing", "0003_embedding_index_dimensions_alter_index_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wikipediadocument",
            name="url",
        ),
        migrations.AddField(
            model_name="document",
            name="url",
            field=models.URLField(default="", unique=True),
            preserve_default=False,
        ),
    ]
